spring:

  # Apache Kafka broker location
  kafka:
    bootstrap-servers: kafka:29092

  application:
    name: coffee_machine

  # Database & JPA properties
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

# Controller urls
coffee:
  # Max portion of coffee
  portion-coefficient:
    max-value: 5
  url: api/v1/coffee
ingredient:
  url: api/v1/ingredient
statistics:
  url: api/v1/stats
auth:
  url: api/v1/auth

# Handled kafka topic
kafka:
  topic: coffee

# JWT signing key
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855