version: '3.9'

services:

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    env_file:
      - zookeeper.env
    expose:
      - "2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
    ports:
      - "29092:29092"
    env_file:
      - kafka.env
    command: /bin/sh -c "sleep 10 && /etc/confluent/docker/run"
    healthcheck:
      test: nc -z kafka 29092 || exit 1
      interval: 5s
      retries: 3
      timeout: 3s


volumes:
  kafka_data:
    driver: local