ALTER SEQUENCE coffee_seq RESTART WITH 53;
ALTER SEQUENCE coffee_prices_seq RESTART WITH 53;
ALTER SEQUENCE coffee_ingredient_seq RESTART WITH 58;
ALTER SEQUENCE ingredient_seq RESTART WITH 54;
ALTER SEQUENCE measurement_seq RESTART WITH 52;
